![New York City schoolbus](schoolbus.jpg)

Photo by [Jannis Lucas](https://unsplash.com/@jannis_lucas) on [Unsplash](https://unsplash.com).
<br>

Every year, American high school students take SATs, which are standardized tests intended to measure literacy, numeracy, and writing skills. There are three sections - reading, math, and writing, each with a **maximum score of 800 points**. These tests are extremely important for students and colleges, as they play a pivotal role in the admissions process.

Analyzing the performance of schools is important for a variety of stakeholders, including policy and education professionals, researchers, government, and even parents considering which school their children should attend. 

You have been provided with a dataset called `schools.csv`, which is previewed below.

You have been tasked with answering three key questions about New York City (NYC) public school SAT performance.

In [89]:
# Re-run this cell 
import pandas as pd

# Read in the data
schools = pd.read_csv("schools.csv")

# Preview the data
schools.head()

# Start coding here...
# Add as many cells as you like...

                                         school_name  ... percent_tested
0  New Explorations into Science, Technology and ...  ...            NaN
1                               Essex Street Academy  ...           78.9
2                       Lower Manhattan Arts Academy  ...           65.1
3    High School for Dual Language and Asian Studies  ...           95.9
4      Henry Street School for International Studies  ...           59.7

[5 rows x 7 columns]

In [90]:
# Get metadata about the database
schools.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375 entries, 0 to 374
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   school_name      375 non-null    object
 1   borough          375 non-null    object
 2   building_code    375 non-null    object
 3   average_math     375 non-null    int64
 4   average_reading  375 non-null    int64
 5   average_writing  375 non-null    int64
 6   percent_tested   355 non-null    float64
dtypes: float64(1), int64(3), object(3)
memory usage: 20.6+ KB

# Which NYC schools have the **best math results**? 

- At least 80% of maximum possible score (>= 80% of 800)
- Save results to DF `best_math_schools`, include "school_name", "average_math", descending order

In [91]:
# Create filter equations
best_math_results = schools['average_math'] >= (0.8 * 800) # >= 640

In [92]:
# Filter the data
high_math_avg = schools.loc[best_math_results, ["school_name", "average_math"]]
high_math_avg_sorted = high_math_avg.sort_values("average_math", ascending=False)

# Save to dataframe
best_math_schools = pd.DataFrame(high_math_avg_sorted)
print(type(best_math_schools))

<class 'pandas.core.frame.DataFrame'>

# What are the **top 10 performing schools** based on the **combined SAT scores**?

In [93]:
# Total SAT
columns_to_sum = ["average_math", "average_reading", "average_writing"]
schools["total_SAT"] = schools[columns_to_sum].sum(axis=1)

# Sort Values by total_SAT 
schools_sorted_by_total_SAT = schools.sort_values(by="total_SAT", ascending=False) 

# limit to top 10 and save to dataframe
top_10_schools = schools_sorted_by_total_SAT.iloc[:10]
top_10_schools = top_10_schools.loc[:, ["school_name", "total_SAT"]]
print(top_10_schools)

                                           school_name  total_SAT
88                              Stuyvesant High School       2144
170                       Bronx High School of Science       2041
93                 Staten Island Technical High School       2041
174  High School of American Studies at Lehman College       2013
333                        Townsend Harris High School       1981
365  Queens High School for the Sciences at York Co...       1947
5                       Bard High School Early College       1914
280                     Brooklyn Technical High School       1896
45                       Eleanor Roosevelt High School       1889
68   High School for Mathematics, Science, and Engi...       1889

# **Which single borough has the largest standard deviation in the combined SAT score?**

In [94]:
# Groupby Borough
borough_summary_stats = schools.groupby('borough').agg(
    num_schools = ('school_name', 'count'),
    average_SAT = ('total_SAT', 'mean'), 
    std_SAT = ('total_SAT', 'std'))
borough_summary_stats = borough_summary_stats.round({
    'num_schools': 0, 
    'average_SAT': 2, 
    'std_SAT': 2})

largest_std = borough_summary_stats["std_SAT"].max()
filter_largest_std = borough_summary_stats["std_SAT"] == largest_std
largest_std_dev = borough_summary_stats.loc[filter_largest_std, :]

largest_std_dev

           num_schools  average_SAT  std_SAT
borough
Manhattan           89      1340.13   230.29